# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Sunny World
tagline:          '강선우의 페이지'
description: >
  The page to organize my days and thoughts.<br />
  B.E. expected in <a href="http://ie.snu.ac.kr" target="_blank">IE</a>
  
url:              http://kangsunwoo827.github.io
baseurl:          /

author:
  name:           'Kang Sunwoo'
  url:            https://www.instagram.com/sun.star.gram/

paginate:         5

# Custom vars
owner:
  name:           Sunwoo Kang
  bio:            "B.S. expected in Industrial Engineering"
  email:          sunday827827@gmail.com
  # Social networking links used in footer. Update and remove as you like.
  facebook:       https://www.facebook.com/profile.php?id=100005674592557
  github:         https://github.com/kangsunwoo827
  linkedin:       https://www.linkedin.com/in/sunwoo-k
  instagram:      https://www.instagram.com/sun.star.gram/
  
category_list: [daily, review, study]

