# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title: Hyde
description:'A brazen two-column <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme that pairs a prominent sidebar with uncomplicated content. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
tagline:'A Jekyll theme'
url: "http://kangsunwoo827.github.io"
github: ChemistryX
email: changeme@chemistryx.me
google_analytics: <YOUR UA TOKEN>
baseurl:          /

exclude: [README.md, Gemfile, Gemfile.lock]

comments:
  enabled: true
  repo: ChemistryX/hyde-comments
  issue-term: pathname
  theme: github-light

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/kangsunwoo827/kangsunwoo827.github.io
