# Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Sunny World
tagline:          '강선우의 페이지'
description:      'The page to organize the days, thought and dream.  This is my <a href="https://github.com/kangsunwoo827" target="_blank">GitHub page</a>'
url:              http://kangsunwoo827.github.io
baseurl:          /


author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.1.0

# theme: jekyll-theme-slate
theme: minima

# disqus: True
github:
  repo:           https://github.com/poole/hyde
