# Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Sunny World
tagline:          '강선우의 페이지'
description:      'The student who wants to be a good person  <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme.'
url:              http://kangsunwoo827.github.io
baseurl:          /


author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.1.0

disqus: True

github:
  repo:           https://github.com/poole/hyde
