# Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Sunny World
tagline:          '강선우의 페이지'
description:      
'The page to organize the days, thoughts and goals.

B.S. expected in <a href="http://ie.snu.ac.kr" target="_blank">IE</a>'

# This is my <a href="https://github.com/kangsunwoo827" target="_blank">GitHub page</a>'

url:              http://kangsunwoo827.github.io
baseurl:          /

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.1.0

theme: minima

      
      
# MyData
owner:
  name:           Sunwoo Kang
  avatar:         photo.jpg
  bio:            "B.S. expected in Industrial Engineering"
  email:          sunday827827@gmail.com
  # Social networking links used in footer. Update and remove as you like.
  facebook:       https://www.facebook.com/profile.php?id=100005674592557
  github:         https://github.com/kangsunwoo827
  linkedin:       https://www.linkedin.com/in/sunwoo-k
  instagram:      https://www.instagram.com/sun.star.gram/

github:
  repo:           https://github.com/poole/hyde
