# Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks
permalink:        pretty
# relative_permalinks: true

# Setup
title:            '선우의 페이지'
tagline:          "Sun's Page"
description:      'Use <a href="http://jekyllrb.com" target="_blank">Jekyll's</a> theme.'
url:              http://kangsunwoo827.github.io
baseurl:          /

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
